### ISSUE TITLE
nosubtype error

### ISSUE THREAD

**Issue by jeffinitelyjeff** [jeffinitelyjeff/Pyty#24]
```
======================================================================
FAIL: test_mod_int_float_conversion6 (__main__.PytyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "_unit_tests_gen.py", line 698, in test_mod_int_float_conversion6
    self._check_mod("test_files/mod_int_float_conversion6.py")
  File "_unit_tests_gen.py", line 125, in _check_mod
    "Shouldn't typecheck, but does:\n%s" % text)
AssertionError: Shouldn't typecheck, but does:
# SUBTYPING
#: x : float
x = 4 + (3.24 - 1432.22 % 3.249)
```

**Comment by jeffinitelyjeff** [comment]
getting some weird error cases becauses augassign branch content is really necessary for nosubtype to achieve its goal.
